version: "3.9"
services:
  web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - ./code:/code
          - ./site.conf:/etc/nginx/conf.d/site.conf
      links:
          - php
      healthcheck:    
        test: rm etc/nginx/conf.d/default.conf
        interval: 1s
        timeout: 10s
        retries: 10
  php:
      image: php:7-fpm
      volumes:
          - ./code:/code
  redis:
    image: redis:latest