---
- name: Ansible Run
  hosts: all
  become: yes

  tasks:
  - name: Repo update
    apt: update_cache=yes force_apt_get=yes

  - name: Install Python
    raw: apt -y install python   

  - name: Install pip
    raw: apt -y install python3-pip   

  - name: Install the Docker package
    raw: apt -y install docker.io

  - name: Start Docker and enter the following command to enable it
    raw: systemctl enable --now docker

  - name: Set user privileges
    raw: usermod -aG docker ${USER}